# Dining
DINING_CEILING: 1
DINING_UPLIGHT: 6

# Sofa
SOFA_CEILING: 2
SOFA_UPLIGHT: 8

#Cupboard
CUPBOARD_TOP: 9
CUPBOARD_BOTTOM: 10

# Others
DESK_LAMP: 5
TV_LIGHTS: 7

# Bedroom room
CARS_LIGHT: 3
BED: 4

